### ISSUE TITLE
Autoswitch $PATH for CLI 

### ISSUE THREAD

**Issue by Goon3r** [philcook/brew-php-switcher#18]
Hello,

Im wondering if a method of auto swithcing the $PATH variable for the PHP CLI can be created for this package? I imagine with the patterns in the .bash_profile declartions this is something that is doable.

```
#export PATH="$(brew --prefix homebrew/php/php56)/bin:$PATH"
export PATH="$(brew --prefix homebrew/php/php70)/bin:$PATH"
```

Thanks for the package, really nice work!

**Comment by philcook** [comment]
@Goon3r I didnt want to mess with users .bash_profiles as there are many custom configs users have done.

Currently it switches the CLI based on unlinking all versions of php and linking up the desired version. See lines [76](https://github.com/philcook/brew-php-switcher/blob/master/phpswitch.sh#L76) and [79](https://github.com/philcook/brew-php-switcher/blob/master/phpswitch.sh#L79).

Does the CLI not switch for you? Are you testing with ```php -v```

**Comment by Goon3r** [comment]
Thanks for the response.

Realised it was a mistake on my part.
On install of homebrew php packages it gives the following caveat
Export line changes depending on versions

`✩✩✩✩ PHP CLI ✩✩✩✩

If you wish to swap the PHP you use on the command line, you should add the following to ~/.bashrc,
~/.zshrc, ~/.profile or your shell's equivalent configuration file:

      export PATH="$(brew --prefix homebrew/php/php70)/bin:$PATH"`

Commenting all of these lines seems to fix this issue.

**Comment by philcook** [comment]
Awesome glad you got things sorted.
