### ISSUE TITLE
Support for php@7.2

### ISSUE THREAD

**Issue by cjwilburn** [philcook/brew-php-switcher#34]
It looks like this issue has been raised before via PR, but not as a proper issue. I'd like some support for PHP v7.2

**Comment by cjwilburn** [comment]
I'll submit a PR to that end. Thanks!

**Comment by black-snow** [comment]
It seems like the `libphp7.so` will now be found at `/usr/local/opt/php72/lib/httpd/modules/libphp7.so` (see https://github.com/Homebrew/homebrew-core/issues/25018).

Is `brew-php-switcher` ready for this?
@cjwilburn @philcook

**Comment by cjwilburn** [comment]
@black-snow would you mind opening a new issue, since this is out of scope of the initial issue? Thanks!
