### ISSUE TITLE
Add support for v7.3

### ISSUE THREAD

**Issue by abolfazl-moeini** [philcook/brew-php-switcher#52]
Hello repository maintainer!

PHP 7.3 is going to release soon and Release Candidate versions are now  available on php.net,
How can we switch to this version?

Thanks indeed

**Comment by cjwilburn** [comment]
It might make sense to wait on this until PHP 7.3 is out of RC and actually released.

**Comment by abolfazl-moeini** [comment]
Thanks, but this tool is for developing stuff and I think it should provide RC, beta, alpha version. 

Please think about that.
Regards

**Comment by ikari7789** [comment]
I’d be more than happy to add support, but this is mainly just a wrapper for existing brew formulas. If brew adds support for installing 7.3, then I can add support here.
