### ISSUE TITLE
Fork for maintainability?

### ISSUE THREAD

**Issue by ikari7789** [philcook/brew-php-switcher#53]
While I’ve been given contributor permissions, this repository requires at least one approval in order to merge PRs, so with the only other contributor being largely inactive, improvements by myself are basically impossible. I’d like to help support some of the issues reported here, but it’s almost impossible. Would the community support me forking this repository and updating the Brew formula accordingly to use the fork?

**Comment by lowbatteries** [comment]
I'd love to see brew-installed Apache supported, I say go for it!

**Comment by GenieTim** [comment]
Did this fork ever happen? Which is the "main" php-switcher repository?

**Comment by philcook** [comment]
@ikari7789 sorry, having a family has taken the spare time I had for this project however I am around more now for this project and I want to get this moving in the right direction again as its been neglected.
