### ISSUE TITLE
Cannot switch to PHP @7.1 

### ISSUE THREAD

**Issue by ravisharmaa** [philcook/brew-php-switcher#55]
I am having issues on switching php @ 7.1 with brew-php-switcher, I have Mojave. Below is the output i get.

```brew doctor
Your system is ready to brew.
```
`brew-php-switcher 7.1`
```➜  ~ brew-php-switcher 7.1
Switching to php@7.1
Switching your shell
Unlinking /usr/local/Cellar/php@7.1/7.1.24_2... 0 symlinks removed
Linking /usr/local/Cellar/php@7.1/7.1.24_2...
Error: Could not symlink bin/pear
Target /usr/local/bin/pear
is a symlink belonging to php. You can unlink it:
  brew unlink php

To force the link and overwrite all conflicting files:
  brew link --overwrite php@7.1

To list all files that would be deleted:
  brew link --overwrite --dry-run php@7.1
You will need sudo power from now on
Switching your apache conf
Password:
Restarting apache
All done!```

``` php -v
PHP 7.2.12 (cli) (built: Nov 29 2018 00:54:39) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.12, Copyright (c) 1999-2018, by Zend Technologies```

**Comment by cfont** [comment]
+1, Had this problem today and could only successfully switch by using `brew link --overwrite php@7.1 --force` before trying to switch the whole thing over. I had the same the problem with the sphp script that I had found as a github script. 

After updating the sphp script with this version (https://gist.github.com/csoseman/f53fc6dd70cf5a382b9fba7f84454961/raw), I don't seem to be having the same problem and hope this recipe will get updated soon.

**Comment by ravisharmaa** [comment]
@cfont should i update the sphp script? from the gist you suggested? @philcook what do you suggest?

**Comment by ravisharmaa** [comment]
@philcook can you please look into this, and release a new tag with this fix, i am having extreme problems with switching

**Comment by ravisharmaa** [comment]
@philcook @cfont since 21 days and still no reply or a release from this, I am very disappointed about the addressing of issue, i believe I should switch on something else for php switching

**Comment by ravisharmaa** [comment]
Thank you guys for not updating, i am using another script. and closing this.
