### ISSUE TITLE
brew-php-switcher still shows either version in iTerm after switching

### ISSUE THREAD

**Issue by handhikadj** [philcook/brew-php-switcher#67]
I have php v5.6, v7.3, and v7.4

When I switch either 7.3 or 7.4 and type `php -v` in iTerm, it still logs me the 5.6 even if `phpinfo()` logs me right. So, when I install laravel with `laravel new my-app`, it shows me error: `This package requires php ^7.2 but your PHP version (5.6.40) does not satisfy that requirement.`

please help

**Comment by philcook** [comment]
@handhikadj ok can I ask are you using bash or zsh or something else. iTerm shouldn't matter really as far as I know as its just the terminal window.
Have you tried with the native terminal program and does this have the same outcome?

**Comment by handhikadj** [comment]
I think everything's fine now
