### ISSUE TITLE
apache not restarted

### ISSUE THREAD

**Issue by bkdotcom** [philcook/brew-php-switcher#68]
brew-php-switcher seems to stop apache just fine... 
it just doesn't seem to restart it for me
I always have to `sudo apachectl -k start` after running brew-php-switcher

thoughts?

**Comment by marcohanke** [comment]
Similar here. httpd stopes and startes but nothing happens. After sudo apachectl -k restart the version switches.
OSX 11.1, homebrew 2.7.7, taps: shivammathur/php
