### ISSUE TITLE
PHP 7.x support

### ISSUE THREAD

**Issue by mirfilip** [philcook/brew-php-switcher#7]
Is there any plan to support PHP 7.x while it's still not stable?

**Comment by philcook** [comment]
@mirfilip just did a brew update myself and saw that php7 was available via brew now. Therefore yes php switcher will support this, I just need to update the code and test it.

Will probably take me a week or so to find the time to do this but feel free to add a PR if you wish

**Comment by philcook** [comment]
@mirfilip I have merge the PHP 7 support to the master branch now and submitted a PR to get homebrew updated.
