### ISSUE TITLE
Unknown version of PHP 8

### ISSUE THREAD

**Issue by Eminlin** [philcook/brew-php-switcher#73]
![image](https://user-images.githubusercontent.com/20252561/100836644-998a6280-34aa-11eb-8e10-b703b362f828.png)  

Unknown version of PHP. PHP Switcher can only handle arguments of: 5.6,7.0,7.1,7.2,7.3,7.4

**Comment by Aredong** [comment]
It seems that the PHP8.0 switch is not supported yet。

**Comment by Eminlin** [comment]
> It seems that the PHP8.0 switch is not supported yet。

yes.
hope can fit in

**Comment by shuvoenr** [comment]
Now they added this.

**Comment by Eminlin** [comment]
Great, thanks
