### ISSUE TITLE
apache config does not change

### ISSUE THREAD

**Issue by eydun** [philcook/brew-php-switcher#83]
Thanks for building this great brew package.

I have used it for switching between php 7.4 and php 8.1 in the terminal. It works great.

But it does not modify the apache httpd config file for the chosen php version. 

I am on Mac (M1 Max). 

Please advice.

**Comment by philcook** [comment]
@eydun can I ask how you have installed apache? Is it the native or via Homebrew?
Also what version on MacOs are you running as they might have changed something in a later version that I need to test and update the code.

**Comment by eydun** [comment]
Thank you for the prompt reply.

>Also what version on MacOs are you running 

It is Monterey ver 12.3.

> how you have installed apache? Is it the native or via Homebrew?

It is via Homebrew. The location of `httpd.conf` is `/opt/homebrew/etc/httpd/`
