### ISSUE TITLE
Tag a new version 2.5 for PHP 8.2 support

### ISSUE THREAD

**Issue by pepijnolivier** [philcook/brew-php-switcher#86]
When I run `brew update && brew upgrade brew-php-switcher`
I'm getting the following output:

```
Already up-to-date.
Warning: brew-php-switcher 2.4 already installed
```

I would like to switch to PHP 8.2 to test some things. I'm seeing the update has already happened, but it looks like we just need to tag a new version for brew

**Comment by DannyvdSluijs** [comment]
See #85 for this.

**Comment by pepijnolivier** [comment]
Alright, thanks! I'll close the issue 🙏
