### ISSUE TITLE
Please support PHP 8.2 and httpd install by homebrew

### ISSUE THREAD

**Issue by codelovercc** [philcook/brew-php-switcher#89]
Please support PHP 8.2 and httpd install by homebrew, Thank you very much.

**Comment by alfianrehanusa** [comment]
up

**Comment by dsuurlant** [comment]
+1

**Comment by eleftrik** [comment]
Is this project still maintained?
As @dsuurlant said, `8.1` and `8.2` versions are listed in brew_array, but I think a new tag/release is needed.

**Comment by jetwu** [comment]
When will version 8.2 be supported？ thanks
